-- Grihasti — product seed (generated from src/data/designs.ts)
-- Stock quantities are PLACEHOLDERS pending the Week-1 production pilot.

insert into products (slug, name, type, description, price_inr, stock_qty, is_active) values ('cool-bhaiya', 'The Cool Bhaiya', 'caricature', 'The effortlessly-swaggy brother — Sunglasses, jacket, relaxed lean', 900, 40, true) on conflict (slug) do nothing;
insert into products (slug, name, type, description, price_inr, stock_qty, is_active) values ('gym-beast', 'The Gym Beast', 'caricature', 'The gains-obsessed brother — Tank, shaker bottle, flexed arm', 900, 25, true) on conflict (slug) do nothing;
insert into products (slug, name, type, description, price_inr, stock_qty, is_active) values ('foodie-bhai', 'The Foodie Bhai', 'caricature', 'Lives for the next meal — Plate of biryani/samosa, happy grin', 900, 40, true) on conflict (slug) do nothing;
insert into products (slug, name, type, description, price_inr, stock_qty, is_active) values ('gamer', 'The Gamer', 'caricature', 'Permanently online — Headset, controller, hoodie', 900, 25, true) on conflict (slug) do nothing;
insert into products (slug, name, type, description, price_inr, stock_qty, is_active) values ('tech-genius', 'The Tech Genius', 'caricature', 'The family''s IT department — Glasses, laptop, hoodie', 900, 15, true) on conflict (slug) do nothing;
insert into products (slug, name, type, description, price_inr, stock_qty, is_active) values ('cricket-fanatic', 'The Cricket Fanatic', 'caricature', 'Weekend warrior — Jersey, bat, mid-celebration', 900, 25, true) on conflict (slug) do nothing;
insert into products (slug, name, type, description, price_inr, stock_qty, is_active) values ('protector', 'The Protector', 'caricature', 'Stern face, softest heart — Arms crossed, warm eyes', 900, 25, true) on conflict (slug) do nothing;
insert into products (slug, name, type, description, price_inr, stock_qty, is_active) values ('drama-queen', 'The Drama Queen', 'caricature', 'Main character energy — Glam pose, dramatic flair', 900, 40, true) on conflict (slug) do nothing;
insert into products (slug, name, type, description, price_inr, stock_qty, is_active) values ('chai-behen', 'The Chai-Fuelled Behen', 'caricature', 'Runs on chai + gossip — Chai cup, cosy shawl', 900, 40, true) on conflict (slug) do nothing;
insert into products (slug, name, type, description, price_inr, stock_qty, is_active) values ('bookworm', 'The Bookworm', 'caricature', 'Always mid-novel — Glasses, stack of books', 900, 15, true) on conflict (slug) do nothing;
insert into products (slug, name, type, description, price_inr, stock_qty, is_active) values ('fashionista', 'The Fashionista', 'caricature', 'Never repeats an outfit — Trendy fit, shopping bags', 900, 25, true) on conflict (slug) do nothing;
insert into products (slug, name, type, description, price_inr, stock_qty, is_active) values ('boss-lady', 'The Boss Lady', 'caricature', 'Ambition in heels — Laptop, coffee, power pose', 900, 25, true) on conflict (slug) do nothing;
insert into products (slug, name, type, description, price_inr, stock_qty, is_active) values ('little-terror', 'The Little Terror', 'caricature', 'Cute, chaotic, beloved — Pigtails/spiky hair, mischievous grin', 900, 40, true) on conflict (slug) do nothing;
insert into products (slug, name, type, description, price_inr, stock_qty, is_active) values ('rakhi-classic', 'The Rakhi Classic', 'caricature', 'The sweet, sentimental one — Traditional outfit, rakhi on wrist', 900, 40, true) on conflict (slug) do nothing;
insert into products (slug, name, type, description, price_inr, stock_qty, is_active) values ('gift-set', 'The Rakhi Gift Set', 'giftset', 'A ready-made signature candle + rakhi + card — Signature candle, rakhi thread, card', 850, 40, true) on conflict (slug) do nothing;
