#!/usr/bin/env bash
#
# Grihasti — one-time server provisioning. Run ON THE SERVER, as root.
#
#   curl -fsSL https://raw.githubusercontent.com/Yogi15490/grihasti/main/scripts/server-setup.sh | bash
#
# or, if the repo is already cloned:
#
#   bash /root/grihasti/scripts/server-setup.sh
#
# It is SAFE TO RE-RUN. Every step checks whether it has already been done.
#
# This box already serves workrize.in, coldpressery.in and farmsae.com. The only
# change made to any of that is ONE APPENDED BLOCK to workrize's Caddyfile, and
# it is backed up and validated before Caddy is reloaded. If validation fails
# the change is reverted automatically and nothing is restarted.

set -Eeuo pipefail

REPO="${REPO:-https://github.com/Yogi15490/grihasti.git}"
APP_DIR="${APP_DIR:-/root/grihasti}"
WORKRIZE_DIR="${WORKRIZE_DIR:-/root/workrize}"
CADDYFILE="$WORKRIZE_DIR/Caddyfile"
DOMAIN="${DOMAIN:-grihasti.in}"

green() { printf '\033[32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[33m%s\033[0m\n' "$*"; }
red() { printf '\033[31m%s\033[0m\n' "$*"; }
step() { printf '\n\033[1m▸ %s\033[0m\n' "$*"; }
die() { red "FAILED: $*"; exit 1; }

trap 'red "Aborted at line $LINENO."' ERR

[ "$(id -u)" = "0" ] || die "Run this as root (you are $(whoami))."

# ── 1. Sanity: is this the right box? ────────────────────────────────────
step "Checking the server"
command -v docker >/dev/null || die "docker is not installed."
[ -d "$WORKRIZE_DIR" ] || die "$WORKRIZE_DIR not found — is this the right server?"
[ -f "$CADDYFILE" ] || die "$CADDYFILE not found."
green "  Docker present, workrize found."

# ── 2. Work out which network Caddy is on ────────────────────────────────
step "Finding Caddy's network"
CADDY_CONTAINER="$(docker ps --filter "ancestor=caddy:2" --format '{{.Names}}' | head -1)"
[ -n "$CADDY_CONTAINER" ] || CADDY_CONTAINER="$(docker ps --format '{{.Names}}' | grep -i caddy | head -1)"
[ -n "$CADDY_CONTAINER" ] || die "No running Caddy container found."

NETWORK="$(docker inspect "$CADDY_CONTAINER" \
  --format '{{range $k,$v := .NetworkSettings.Networks}}{{$k}} {{end}}' | awk '{print $1}')"
[ -n "$NETWORK" ] || die "Could not determine Caddy's network."
green "  Caddy is '$CADDY_CONTAINER' on network '$NETWORK'."

# ── 3. Clone or update the repo ──────────────────────────────────────────
step "Fetching the code"
if [ -d "$APP_DIR/.git" ]; then
  git -C "$APP_DIR" pull --ff-only && green "  Updated existing clone."
else
  if ! git clone "$REPO" "$APP_DIR" 2>/dev/null; then
    red "  Clone failed — the repo is private and this server can't authenticate."
    echo ""
    echo "  Fix it with a GitHub token (classic, 'repo' scope):"
    echo "    git clone https://YOUR_TOKEN@github.com/Yogi15490/grihasti.git $APP_DIR"
    echo "  then re-run this script."
    exit 1
  fi
  green "  Cloned into $APP_DIR."
fi

# ── 4. Environment file ──────────────────────────────────────────────────
step "Environment file"
if [ -f "$APP_DIR/.env" ]; then
  green "  $APP_DIR/.env already exists — leaving it alone."
else
  DB_PASSWORD="$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)"
  cat > "$APP_DIR/.env" <<EOF
# Generated by server-setup.sh on $(date -u +%F)
DB_NAME=grihasti
DB_USER=grihasti
DB_PASSWORD=$DB_PASSWORD

WORKRIZE_NETWORK=$NETWORK

NEXT_PUBLIC_SITE_URL=https://$DOMAIN
GST_RATE=0.18

# Fill these in as the accounts arrive — see docs/GO_LIVE_ACCOUNTS.md.
# The site runs without them; only email sign-in and payments need them.
RESEND_API_KEY=
EMAIL_FROM="Grihasti <hello@$DOMAIN>"
RAZORPAY_KEY_ID=
RAZORPAY_KEY_SECRET=
RAZORPAY_WEBHOOK_SECRET=
SHIPROCKET_EMAIL=
SHIPROCKET_PASSWORD=
NEXT_PUBLIC_META_PIXEL_ID=
EOF
  chmod 600 "$APP_DIR/.env"
  green "  Created $APP_DIR/.env with a generated database password."
fi

# Make sure the network name is right even on a pre-existing .env.
if ! grep -q '^WORKRIZE_NETWORK=' "$APP_DIR/.env"; then
  echo "WORKRIZE_NETWORK=$NETWORK" >> "$APP_DIR/.env"
fi

# ── 5. Build and start ───────────────────────────────────────────────────
step "Building and starting grihasti (this takes a few minutes)"
cd "$APP_DIR"
# --force-recreate: a stale container holding the fixed container_name makes
# compose exit with a name conflict while the OLD container keeps serving, so
# the deploy appears to succeed and changes nothing.
docker rm -f grihasti-web >/dev/null 2>&1 || true
docker compose up -d --build --force-recreate --remove-orphans \
  || die "docker compose failed. Check the output above."

echo "  Waiting for the app to become healthy..."
for i in $(seq 1 30); do
  if docker exec grihasti-web node -e \
      "fetch('http://127.0.0.1:3000/login').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))" \
      2>/dev/null; then
    green "  App is responding."
    break
  fi
  [ "$i" = "30" ] && {
    red "  App did not come up. Recent logs:"
    docker compose logs --tail 40 web
    die "grihasti-web is not healthy."
  }
  sleep 3
done

# ── 6. Caddy: add the site block ─────────────────────────────────────────
step "Telling Caddy about $DOMAIN"
if grep -q "^${DOMAIN}" "$CADDYFILE" || grep -q "grihasti-web" "$CADDYFILE"; then
  green "  Caddyfile already has a $DOMAIN block — not touching it."
else
  BACKUP="$CADDYFILE.bak.$(date +%s)"
  cp "$CADDYFILE" "$BACKUP"
  yellow "  Backed up Caddyfile to $BACKUP"

  # Automatic TLS, no Cloudflare client-certificate requirement.
  #
  # workrize.in uses `client_auth require_and_verify` against the Cloudflare
  # origin-pull CA. That only works when the zone has Authenticated Origin
  # Pulls switched on AND traffic is proxied through Cloudflare. grihasti.in
  # points straight at this box, so demanding a client cert made Caddy reject
  # Let's Encrypt's own validation request and no certificate could ever be
  # issued. This config works whether or not Cloudflare sits in front.
  #
  # To harden later: put the domain behind Cloudflare (orange cloud), enable
  # Authenticated Origin Pulls for the zone, THEN add the client_auth block.
  cat >> "$CADDYFILE" <<EOF

$DOMAIN, www.$DOMAIN {
	reverse_proxy grihasti-web:3000
}
EOF

  # Validate BEFORE reloading. A bad Caddyfile would take down three live
  # sites, so a failed validation reverts and stops here.
  if docker exec "$CADDY_CONTAINER" caddy validate --config /etc/caddy/Caddyfile >/dev/null 2>&1; then
    green "  Caddyfile validates."
  else
    cp "$BACKUP" "$CADDYFILE"
    red "  Caddyfile did not validate — reverted. workrize.in is untouched."
    docker exec "$CADDY_CONTAINER" caddy validate --config /etc/caddy/Caddyfile || true
    die "Caddy config invalid."
  fi

  docker exec "$CADDY_CONTAINER" caddy reload --config /etc/caddy/Caddyfile \
    || die "Caddy reload failed. Restore with: cp $BACKUP $CADDYFILE"
  green "  Caddy reloaded. Existing sites were not restarted."
fi

# ── 7. Nightly backup ────────────────────────────────────────────────────
step "Nightly database backup"
if crontab -l 2>/dev/null | grep -q "grihasti.*pg_dump"; then
  green "  Backup cron already installed."
else
  mkdir -p /var/backups/grihasti
  ( crontab -l 2>/dev/null || true
    echo "15 3 * * * cd $APP_DIR && docker compose exec -T db pg_dump -U grihasti grihasti | gzip > /var/backups/grihasti/\$(date +\\%F).sql.gz 2>/dev/null"
  ) | crontab -
  green "  Nightly pg_dump at 03:15 into /var/backups/grihasti/."
  yellow "  NOTE: local only. Copy offsite before taking real orders —"
  yellow "  the points ledger is money owed to customers."
fi

# ── Done ─────────────────────────────────────────────────────────────────
printf '\n\033[1;32m════════════════════════════════════════════\033[0m\n'
green "grihasti is running."
printf '\033[1;32m════════════════════════════════════════════\033[0m\n\n'
echo "  Containers:"
docker ps --filter name=grihasti --format '    {{.Names}}  {{.Status}}'
echo ""
echo "  Next: point DNS in Cloudflare, both PROXIED (orange cloud):"
echo "    A   @     $(curl -s -4 ifconfig.me 2>/dev/null || echo '<this server IP>')"
echo "    A   www   $(curl -s -4 ifconfig.me 2>/dev/null || echo '<this server IP>')"
echo ""
echo "  Then open: https://$DOMAIN"
echo ""
echo "  From now on, pushing to main deploys automatically."
echo ""
